github.com:
    users:
        GohilVishal0180:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: GohilVishal0180
